python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.05 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.05 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.05 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.03 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.03 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.03 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.01 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.01 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.01 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.5 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 140
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.5 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 140
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.5 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 140
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.3 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.3 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.3 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.1 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.1 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.1 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.05 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.05 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.05 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.03 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.03 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.03 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.01 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.01 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar100 --dataset_root=./dataset/CIFAR100 --proto_case=Case3  --partial_rate=0.01 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.5 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 140 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.5 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 140 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.5 --noise_rate=0.3  --epochs=2000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 140 --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.3 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80  --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.3 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80  --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.3 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80  --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.1 --noise_rate=0.1  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80  --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.1 --noise_rate=0.2  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80  --loss_weight_mixup 0
python -u train_merge.py --seed=0 --save_root=savefinals --dataset=cifar10  --dataset_root=./dataset/CIFAR10  --partial_rate=0.1 --noise_rate=0.3  --epochs=1000 --encoder=resnet --lr=0.01 --lr_adjust=Case1 --optimizer=sgd --weight_decay=1e-3 --gpu=0 --max1 --piror_start 80  --loss_weight_mixup 0
